### ISSUE TITLE
[FlamingoForConditionalGeneration] Loading huggingface models

### ISSUE THREAD

**Issue by llnns** [Luodian/Otter#251]
The following code to load "luodian/openflamingo-9b-hf" for ConditionalGeneration:

```python
from flamingo import FlamingoForConditionalGeneration
model = FlamingoForConditionalGeneration.from_pretrained("luodian/openflamingo-9b-hf")
```

Resulted in:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/dist-packages/transformers/modeling_utils.py", line 2700, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "/Otter/flamingo/modeling_flamingo.py", line 713, in __init__
    if config.text_config.architectures[0] == "MPTForCausalLM":
TypeError: 'NoneType' object is not subscriptable
```
Based on the FlamingoModel Class, I noticed the following comment [line](https://github.com/Luodian/Otter/blob/93a0d5e2d6f114e70d6e327b975bce4671cea9bb/flamingo/modeling_flamingo.py#L712), when I uncomment it, the model loads correctly.

**Comment by Luodian** [comment]
ok I see it's a bug from our side. we overlooked some config files dont have this attribute.

Could you start with `luodian/OTTER-MPT1B-RPJama-Init`?

**Comment by Luodian** [comment]
This one should be fine since it's our latest used model.
