### ISSUE TITLE
Gradio

### ISSUE THREAD

**Issue by WangQvQ** [Luodian/Otter#263]
Hello, your work is excellent , will gradio pages be open source ？🫣

**Comment by Luodian** [comment]
Sure, our demo has been opensourced, you could take a look at `pipeline/serve`, the whole folder contains demo code.

And you could see `docs/host.md` to check how to run this demo.

**Comment by twmht** [comment]
@Luodian 

I just got the errors when launching the controller

```
Traceback (most recent call last):                                                                                                                                                                  File "/home/acer/.pyenv/versions/3.9.16/lib/python3.9/runpy.py", line 197, in _run_module_as_main                                                                                                   return _run_code(code, main_globals, None,                                                                                                                                                      File "/home/acer/.pyenv/versions/3.9.16/lib/python3.9/runpy.py", line 87, in _run_code                                                                                                              exec(code, run_globals)                                                                                                                                                                         File "/home/shared/Otter/pipeline/serve/model_worker.py", line 23, in <module>                                                                                                                      from pipeline.constants import WORKER_HEART_BEAT_INTERVAL                                                                                                                                     ModuleNotFoundError: No module named 'pipeline.constants' 
```
